# Generated by Django 2.1.1 on 2018-10-05 19:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelInformation', '0002_auto_20181005_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('attrs', django_mysql.models.JSONField(default=dict)),
                ('weather', django_mysql.models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
